### ISSUE TITLE
CLEAN4: Multiple activations of same object during animation

### ISSUE THREAD

**Issue by ReenBean0** [ReenBean0/Toadm-n#11]
Example:
A moving object has two buttons
Left button moves it left, right button moves it right
Press left button and then shortly after, press right button. Apocalypse

There should be some sort of cooldown on the object or state checker that stops it from being activated until the previous activation has been completed

**Comment by ReenBean0** [comment]
Does the isOn or isActive condition fix this?

**Comment by henrypaul2001** [comment]
It does actually
