### ISSUE TITLE
CLEAN3: Tongue max fire distance and collision problems (R: DEV 9)

### ISSUE THREAD

**Issue by ReenBean0** [ReenBean0/Toadm-n#12]
Tongue should only be able to reach a certain max distance

ALSO

If the tongue collides with an object before reaching the target position, it should interrupt the animation and stop at the collision point to make sure the tongue doesn't pass through objects

**Comment by ReenBean0** [comment]
Being able to hit multiple objects might be a good puzzle mechanic, but platforms should stop the tongue from reaching objects.

**Comment by henrypaul2001** [comment]
Waiting for the tongue rework to be complete, not sure how the collisions will work with new system yet
